### ISSUE TITLE
Finalize the Hardware List

### ISSUE THREAD

**Issue by ishchow** [ECE-492-W2020-Group-6/smart-blinds-rpi#1]
Todo:
- [x] Talk to someone about motor sizing
- [x] Pick motor and controller
- [x] Start ordering parts on Friday

GanttStart: 2020-01-22
GanttDue: 2020-01-24

**Comment by ishchow** [comment]
@samjwu @AY-Chen @kdehaan 

I've come up with a finalized hardware list

**Platform:** [Raspberry Pi 3 Model B](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/ ) [Unchanged]
- Have this on hand (no need to buy)

**Temperature Sensor:** [Bosch BME280 Environmental Sensor](https://www.amazon.ca/BME280-Environmental-Sensor-Temperature-barometric/dp/B07GZCZFVG/ref=sr_1_10?keywords=raspberry%2Bpi%2Btemperature%2Bsensor&qid=1579415315&sr=8-10&th=1) [Unchanged]

**Motor:** [SparkFun ROB-09238 12V 330mA 230 mNm Bi-polar Stepper Motor](https://www.digikey.ca/product-detail/en/sparkfun-electronics/ROB-09238/1568-1105-ND/5318747)

**Motor Controller:** [SparkFun Easy Driver](https://www.digikey.ca/product-detail/en/sparkfun-electronics/ROB-12779/1568-1108-ND/5318750)
- Supply controller with anywhere from 6 - 30 V, 2 A DC
- Controller outputs 150 mA - 750 mA based on potentiometer position (meets our requirement of 330 mA)
- Guaranteed compatibility with Servo since manufacturer documentation for driver assumes use of the SparkFun ROB-09238 servo

**Motor Power Supply:** [Signcomplex 12 V 2 A Switching Power Supply](https://www.amazon.ca/Adapter-Supply-Switching-100-240V-Transformer/dp/B0711SZCMQ/ref=sr_1_5?crid=2FD8WVE3ZMJP8&keywords=12v+2a+power+supply+with+connector&qid=1579920089&sprefix=12v+2+A+%2Caps%2C487&sr=8-5)
- Replaced old power supply since this power supply has better ratings and is currently cheaper

**Raspberry Pi Power Supply:** [CanaKit Raspberry Pi Power Supply](https://www.amazon.ca/CanaKit-Raspberry-Supply-Adapter-Listed/dp/B0131AYG8C/ref=sr_1_1?keywords=canakit+raspberry+pi+power+supply&qid=1579551803&sr=8-1)
- Have this on hand (no need to buy)

**Female Headers:** Any will do
- Need this since Easy Driver doesn't come with header soldered on, have to solder ourselves
- Probably don't have to buy this

**Jumper Wires:** Any will do
- Probably have enough from various lab kits

**Comment by ishchow** [comment]
I didn't have to talk to Reagan since the motor controller and stepper are designed to work together. They are both rated at the same voltage so we can use the 12 V power supply with it safely. The documentation for the driver is fairly straightforward. They are both also relatively inexpensive. 

SparkFun also sells a slightly more expensive 12 V 1.7 A 480 mNm stepper motor that can be controlled with the SparkFun Big Easy Driver. But I decided against using it since the Big Easy Driver can only supply 1.4 A to a stepper motor at room temperature. Supplying 1.7 A would require a heat sink or a fan. I think we can safely relax the torque requirements to ~200 mNm which can be controlled safely at room temperature. Also, the big easy driver seems much larger than the Easy Driver and would probably not fit within/near the blinds.

**Comment by ishchow** [comment]
Let me know what you guys think of the parts. If you're cool with it, I can begin ordering parts.

**Comment by samjwu** [comment]
Hookup Guide for Stepper Motor/Driver:
https://media.digikey.com/pdf/Data%20Sheets/Sparkfun%20PDFs/EasyDriver_Hookup_Guide_Web.pdf

**Comment by ishchow** [comment]
Parts ordered. See https://drive.google.com/drive/u/0/folders/1e0sDLKNl6rG0xsryfq-ShgqEIdzYW5mP for receipts.
