### ISSUE TITLE
Determine specifics of external application

### ISSUE THREAD

**Issue by kdehaan** [ECE-492-W2020-Group-6/smart-blinds-rpi#15]
Compare and decide between android/pwa/etc for controlling the system via phone

GanttStart: 2020-01-22
GanttDue: 2020-01-29

**Comment by ishchow** [comment]
More architecture  diagrams and stuff for this would be good for the CDR and presentation. As well as interactions with the REST API.

**Comment by kdehaan** [comment]
Additionally, investigate what is the best type of webserver (node.js/flask/etc)
