### ISSUE TITLE
Create tentative architectural diagram

### ISSUE THREAD

**Issue by kdehaan** [ECE-492-W2020-Group-6/smart-blinds-rpi#16]
Initial investigation into how the overall system architecture will work; not required to be the final version

Design Artifacts for Architecture:
- [x] High Level Architecture
- [x] State Flowchart
- [x] Pseudocode Algorithm

GanttStart: 2020-01-22
GanttDue: 2020-01-29

**Comment by samjwu** [comment]
https://drive.google.com/drive/folders/1uv3fSQcNrh93zl-RnIt2RDzelDqXscyE
