### ISSUE TITLE
Initial Design and Testing of Motor Algorithm

### ISSUE THREAD

**Issue by ishchow** [ECE-492-W2020-Group-6/smart-blinds-rpi#2]
- Design motor algorithm and test using fake data

GanttStart: 2020-01-29
GanttDue: 2020-02-03

**Comment by samjwu** [comment]
Pseudocode - https://docs.google.com/document/d/1LkXmi4Jsk9RHf-r7s4PpNg3KcTrgrspVJb_FGHpVXVY/edit

Behavior - https://docs.google.com/document/d/1WCAtJ1-xvY9vYspOzB-Mh_lGReM_5XbDVeEHXQCPUMA/edit
