### ISSUE TITLE
Prepare Answers for Possible Questions during Presentation

### ISSUE THREAD

**Issue by ishchow** [ECE-492-W2020-Group-6/smart-blinds-rpi#27]
We'll make a google doc that has some answers for possible questions people can ask during design reviews.

Ex.
Why use a stepper motor vs servo motor?
Why not lift the blinds too?

etc

GanttStart: 2020-01-29
GanttDue: 2020-02-03

**Comment by samjwu** [comment]
https://docs.google.com/document/d/1U676caAFiOEK628jz9cvanbgiYquAd9l7xaYE5Xy7BU/edit
