### ISSUE TITLE
Circuit Diagram/Design

### ISSUE THREAD

**Issue by AY-Chen** [ECE-492-W2020-Group-6/smart-blinds-rpi#5]
Create the circuit diagram for connections between our components. 

GanttStart: 2020-01-29
GanttDue: 2020-02-03

**Comment by ishchow** [comment]
Hardware documentation1-page block diagram of hardware (including components used on FPGA board)Full (hierarchical) schematics showing all components (FPGA boards and other modules may be represented as one component.

**Comment by ishchow** [comment]
Schematics (both images and editable form) is located here: https://drive.google.com/drive/u/1/folders/1R7wGoxzCfMpfxoZKmiss7LXV2-7tOCWf

Schematic is created using [Fritzing](https://fritzing.org/home/), to make further changes edit the .fzz file and reupload new .fzz file (and re-export images) when done.
