### ISSUE TITLE
Create test procedure for hardware

### ISSUE THREAD

**Issue by ishchow** [ECE-492-W2020-Group-6/smart-blinds-rpi#6]
- create test procedure for temperature sensor
- create test procedure for motor

GanttStart: 2020-01-22
GanttDue: 2020-01-29

**Comment by ishchow** [comment]
GanttStart: 2020-01-22
GanttDue: 2020-01-29

**Comment by AY-Chen** [comment]
Hardware test plan completed. 
Link to document: https://docs.google.com/document/d/1R_LaFEwYrrMuiXPvjyLhxYfsPKrGc5jtUJvRvnfffFM/edit
