### ISSUE TITLE
Research Voice Control

### ISSUE THREAD

**Issue by ishchow** [ECE-492-W2020-Group-6/smart-blinds-rpi#74]

**Comment by samjwu** [comment]
https://pypi.org/project/SpeechRecognition/

**Comment by ishchow** [comment]
Offline, real-time speech recognition using Mozilla DeepSpeech:
- https://github.com/mozilla/DeepSpeech
- https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/
- https://github.com/mozilla/DeepSpeech-examples

Potential microphone candidates:
- https://www.amazon.ca/Omnidirectional-Computer-Microphone-Sensitivity-Meeting%EF%BC%88White%EF%BC%89/dp/B07PV6NC39/ref=sr_1_44?keywords=desktop%2Bmicrophone&qid=1583798377&sr=8-44&th=1
- https://www.amazon.ca/Neewer-Driver-free-Desktop-Computer-Microphone/dp/B07NJMHT1Q/ref=sr_1_10?keywords=microphone+conference&qid=1583798905&sr=8-10
- https://www.amazon.ca/Seeed-Studio-ReSpeaker-2-Mics-Hat/dp/B07CXSW6LB/ref=pd_sbs_147_3/130-0484858-7879830?_encoding=UTF8&pd_rd_i=B07CXSW6LB&pd_rd_r=ba940f19-c380-4700-8524-691be22d8bc8&pd_rd_w=lmjfG&pd_rd_wg=4JO08&pf_rd_p=74b54c94-7195-4620-ba51-7d167ac58a58&pf_rd_r=8ZNAEGB8X5CNJDC8SK7K&psc=1&refRID=8ZNAEGB8X5CNJDC8SK7K
        - designed for rpi but uses entire 40 pin header

**Comment by ishchow** [comment]
https://github.com/ShailChoksi/text2digits
